version: "3.8"

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
